# Generated by Django 6.0.3 on 2026-03-24 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_hotel_chatmessage_hotelroom_hotelroombooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedroom',
            name='available_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listedroom',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma separated tags/amenities', null=True),
        ),
    ]
