# Generated by Django 6.0.3 on 2026-03-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_bookinghistory_created_at_bookinghistory_is_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='related_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
