# Generated by Django 6.0.3 on 2026-03-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_appnotification_related_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotification',
            name='notification_type',
            field=models.CharField(choices=[('PROFILE', 'Profile'), ('ACCOUNT', 'Account'), ('ROOM', 'Room'), ('CHAT', 'Chat'), ('BOOKING', 'Booking'), ('MATCH', 'Match')], default='PROFILE', max_length=20),
        ),
    ]
