# Generated by Django 6.0.3 on 2026-03-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_userprofile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='directchatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='direct_chat_images/'),
        ),
        migrations.AddField(
            model_name='directchatmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('ROOM_SHARE', 'Room Share')], default='TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='directchatmessage',
            name='room_baths',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='directchatmessage',
            name='room_beds',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='directchatmessage',
            name='room_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='directchatmessage',
            name='room_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='directchatmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
