# Generated by Django 6.0.3 on 2026-03-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_directchatmessage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='roomtourschedule',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='groupchatmember',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='groupchatmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupchatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='roomtourschedule',
            name='requested_by',
        ),
        migrations.DeleteModel(
            name='GroupChat',
        ),
        migrations.DeleteModel(
            name='GroupChatMember',
        ),
        migrations.DeleteModel(
            name='GroupChatMessage',
        ),
        migrations.DeleteModel(
            name='RoomBooking',
        ),
        migrations.DeleteModel(
            name='RoomTourSchedule',
        ),
    ]
